[project]
name = "metablock"
description = "Metablock cloud python client"
version = "1.2.0"
license = "BSD"
readme = "readme.md"
authors = [
    { name = "Luca Sbardella", email = "luca@quantmind.com" },
]
requires-python = ">=3.11,<3.15"
dependencies = [
    "httpx >= 0.28.1",
    "multidict >= 6.4.3",
    "pydantic (>=2.12.5,<3.0.0)",
]

[project.optional-dependencies]
cli = [
    "click >= 8.1.7",
    "pyyaml >= 6.0.2",
    "jinja2 >= 3.1.6",
]
dev = [
    "pytest-asyncio >= 1.3.0",
    "pytest >= 9.0.2",
    "pytest-cov >= 7.0.0",
    "mypy >= 1.19.1",
    "black >= 26.1.0",
    "isort >= 8.0.1",
    "python-dotenv >= 1.2.2",
    "types-pyyaml >= 6.0.12.20240917",
    "ruff >= 0.15.4",
]

[build-system]
requires = [ "poetry-core>=1.0.0" ]
build-backend = "poetry.core.masonry.api"

[project.scripts]
metablock = "metablock.cli:main"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "module"
testpaths = [ "tests" ]

[tool.ruff]
lint.select = [ "A", "E", "W", "F", "I", "B", "N" ]
line-length = 88

[tool.mypy]
disallow_untyped_calls = true
warn_return_any = false
disallow_untyped_defs = true
warn_no_return = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false
