#!/usr/bin/env bash
set -e

BLACK_ARG="--check"
RUFF_ARG=""

if [ "$1" = "fix" ] ; then
    BLACK_ARG=""
    RUFF_ARG="--fix"
fi

echo "run black"
uv run black metablock tests ${BLACK_ARG}
echo "run ruff"
uv run ruff check metablock tests ${RUFF_ARG}
echo "run mypy"
uv run mypy metablock tests
