name: build

on:
  push:
    branches-ignore:
      - deploy
    tags-ignore:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON_ENV: ci
      METABLOCK_API_TOKEN: ${{ secrets.METABLOCK_API_TOKEN }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make install
      - name: run lint
        run: make test-lint
      - name: run tests
        run: make test
      - name: upload coverage
        if: matrix.python-version == '3.13'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/coverage.xml
      - name: release
        if: ${{matrix.python-version == '3.13' && github.ref == 'refs/heads/main' && github.event.head_commit.message == 'release'}}
        run: make publish
